version: '3.8'

services:
  db:
    image: postgres
    container_name: go_twitter_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_twitter
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: